---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook docker-netdata/tests/test.yml -i docker-netdata/tests/inventory --syntax-check
  - ansible-playbook docker-csgo-server/tests/test.yml -i docker-csgo-server/tests/inventory --syntax-check
  - ansible-playbook docker-netbootxyz/tests/test.yml -i docker-netbootxyz/tests/inventory --syntax-check
  - ansible-playbook docker-yt-dl/tests/test.yml -i docker-yt-dl/tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
